### ISSUE TITLE
Define email to be sent to user with referral link

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-server#144]
Define the contents of the email which will be sent to the user when they give us their email address for a referral.

Child of Volentix/venue#8

**Comment by shawnlauzon** [comment]
@volentixnonton11 @Mojganahk Will the final version of this be ready soon?

**Comment by Mojganahk** [comment]
@shawnlauzon I sent the HTML file tto the email.

**Comment by shawnlauzon** [comment]
Got it, thanks.
