### ISSUE TITLE
Registration and invite a friend emails not set

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-server#165]
**Describe the bug**
I no longer am receiving emails for registration, or for inviting a friend. The registration emails at least are a regression.

**To Reproduce**
1. Click on sign up
2. Enter email, username, and password
3. Click signup
4. Never receive email

**Expected behavior**
I should receive a registration email.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by alexdashkov** [comment]
As I see API send a good response for the sent emails, however, I don't receive emails. Can you check what's going on with the service you use?

**Comment by shawnlauzon** [comment]
I found the problem, the postmark token needs to be set because it is no longer in the repository.

Now, users need to create a `.env` file with a line:
`POSTMARK_SERVER_TOKEN=<server_token>`

otherwise emails are not sent out. I also updated the README.

Fixed in [680007](https://github.com/Volentix/venue-server/commit/680007d24d8fcfb904aadc8f910ffec38132fb7e)
