### ISSUE TITLE
Final version of referral bonus email

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-server#173]
[Here is the HTML email](https://github.com/Volentix/venue-server/files/2283872/referral_email.html.zip) which should be sent out for the referral bonus.

Please note that there are two bits of replacement text:

- `${referrer_name}` - The username of the person who is sending the referral
- `${referral_url}` -  The URL for signup with the referral code.

Child of Volentix/venue#8

**Comment by shawnlauzon** [comment]
I think the subject should be: "You have been referred to our Bitcoin Talk signature campaign!"

@Mojganahk @volentixnonton11 If either of you think it should be something else, please add it here, thanks.

**Comment by volentixnonton11** [comment]
"Referral to Volentix Bitcointalk.org signature campaign" is better on it's
own in my opinion.

I think that "You have been" as entry words might get flagged as spam more
often and also might subliminally affect people negatively.

**Comment by shawnlauzon** [comment]
@alexdashkov Please update subject as noted above, thanks.

**Comment by shawnlauzon** [comment]
@alexdashkov I still see the original subject line; not sure how it got lost.
