### ISSUE TITLE
Email for Turkish users

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-server#181]
It looks like the referral bonus email text messages are not part of the translation file, which means they can't be translated. These need to be added to the `.po` file and then sent to translation.

cc @Mojganahk

**Comment by Mojganahk** [comment]
Please make sure the file contains all the phrases which needs to be translated.

**Comment by shawnlauzon** [comment]
After seeing the commit from @alexdashkov, I've realized that putting all the HTML in the `.po` file is a bad idea (hadn't really thought it through). The entire file should be translated.

However, the other question is if we should really be sending Turkish referrals to all the friends of a Turkish user? Or should the referral email be sent in English? This is a question for @volentixnonton11 or @vlabs-mar.

**Comment by shawnlauzon** [comment]
@Mojganahk asked for all of the options. Here they are that I can think of:

1. Always send English email
2. Send Turkish email if sender is Turkish
3. Drop down on client side choosing language to send *all* emails in
4. Drop down on client side choosing language to send *each* email in
4. Send English email if sender is Turkish, but that also includes a link to a hosted copy of the referral email in Turkish (this hosted version in fact can display the referral link if we host the email on Venue)
5. Send all languages in email (probably won't fit)
6. Shrink the size of the email content in order to put all languages (might fit for ~2 languages)

Let me know what @Mojganahk and @volentixnonton11 decide.

**Comment by volentixnonton11** [comment]
5 and 7 seem most appropriate to me.

Sending only Turkish emails is ruled out because if it is an English
receiver and they flag as spam because it's Turkish and they can't
understand anything that has long term threat attached.

@mojganhk ?

**Comment by Mojganahk** [comment]
@volentixnonton11 @shawnlauzon  Number 5 can be a good option.
