### ISSUE TITLE
Turkish version of referral email

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-server#190]
This will be hosted on Venue.

- [x] Text for Turkish email
- [x] Turkish text which will be embedded into the English email to point the user to this Turkish email
- [x] Information on where in the English email the Turkish text will be placed.

Child of #181

**Comment by shawnlauzon** [comment]
@Mojganahk This is the file which needs to be translated: note that it's not exactly the same one that you sent originally (needed some changes), so please use this for future translations.

**Comment by Mojganahk** [comment]
Turkish sentence which comes at the FIRST of the Turkish Email(it means for reading this email in english please click here):

>>>>  Bu epostayı İngilizce olarak okumak için lütfen buraya tıklayın

======================================================
English sentence which comes at the FIRST of the English Email:

>>>>   For the Turkish Version of the following newsletter, please click here.

**Comment by Mojganahk** [comment]
@shawnlauzon 

it means for reading this email in TURKISH please click here

>> Bu epostayı Türkçe olarak okumak için lütfen buraya tıklayın

**Comment by shawnlauzon** [comment]
@alexdashkov Please see above for the text which should be added to the English language html.

**Comment by Mojganahk** [comment]
@alexdashkov 
we will add this : 

> Bu epostayı Türkçe olarak okumak için lütfen buraya tıklayın

at the beginning of the english email (it means For the Turkish Version of the following newsletter, please click here.) .

**Comment by alexdashkov** [comment]
@shawnlauzon, @Mojganahk are we all agreed that this text should be added **only** if user has `tr` as his language?

**Comment by shawnlauzon** [comment]
@alexdashkov Yes, that is correct.
