### ISSUE TITLE
Generate mo files. 

### ISSUE THREAD

**Issue by alexdashkov** [Volentix/venue-server#197]
I see that you made a translation for the Turkish but I still do not see `*.mo` files. Do you generate them during the deploy or you do not generate them? 

I wrote details in this PR https://github.com/Volentix/venue-server/pull/132 and this is a link to the doc 
https://docs.djangoproject.com/en/1.11/ref/django-admin/#compilemessages

**TLDR:** 
You should run a command `docker-compose run --rm web django-admin compilemessages` to compile `*.mo` files and make a translation work. 

**P.S.:**
I'm not sure that we should add these files to the git, but better to generate them during the deployment.

**Comment by shawnlauzon** [comment]
I have never done anything with .mo files. And it sounds fine to me that
they be generated in the build. Please add that to the build script, thanks.
