### ISSUE TITLE
Circle CI build failed

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-server#199]
The change to build `.mo` files seems to have broken the build:

![image](https://user-images.githubusercontent.com/611529/44304293-26cf3a80-a326-11e8-8b98-dc98c4346e4f.png)

https://circleci.com/gh/Volentix/venue-server/337?utm_campaign=build-failed&utm_content=failing-command&utm_medium=email#tests/containers/0/actions/110

Please take a look and resolve.

Also given that it can break the build, we should build the `.mo` files for every branch, not just on the master branch.

**Comment by alexdashkov** [comment]
oh, I forgot that circleci can't work with volumes. 
> we should build the .mo files for every branch, not just on the master branch.

I don't see a way to build the files for each branch in the CircleCI. I mean that I'm about to add the files to the image that ci pushes to the repository and we do it only for the master. If you want to have the files into every branch, we have to keep them in the git instead and just re-compile them when you change translations.

**Comment by shawnlauzon** [comment]
We don't need to keep the files, just to build them -- that is, if it is possible for the build process to fail. If the build process can never fail, then you're right, they only need to be in master.

Basically, if it's possible for a part of the build to fail, it should be done in every branch.

**Comment by alexdashkov** [comment]
Ok, I see your point. And yes it's possible that it will be failed. So I'll add it just after the tests.
