### ISSUE TITLE
Referral email has poor visual formatting and does not match the good formatting on website

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-server#238]
**Describe the bug**
The referral email seems to have some formatting issues; see screenshots.

**To Reproduce**
1. Send a referral email
2. Open email (I'm using gmail on chrome)

**Expected behavior**
The same formatting for the email as that on the website (the website is in Turkish but the email is in English; this is how it should be).

**Screenshots**
The formatting seems to have to do with centering: everything is pushed left. Also there are some hard line breaks in the email which should not be there; they are correct in the website.

From the email
![image](https://user-images.githubusercontent.com/611529/45099291-e973f680-b0f4-11e8-802b-16021260e781.png)

And the website:
![image](https://user-images.githubusercontent.com/611529/45099268-de20cb00-b0f4-11e8-9b31-436fb46553c8.png)

Also the pillars are formatted poorly. Email:
![image](https://user-images.githubusercontent.com/611529/45099307-f7c21280-b0f4-11e8-8305-a79ddb201ecf.png)

Website:
![image](https://user-images.githubusercontent.com/611529/45099321-fe508a00-b0f4-11e8-9870-c0daea582cb7.png)

**Additional context**

**Comment by Lyncis** [comment]
Fixed the formatting and checked it through venue-dev. It is fixed now. These are screenshots from my gmail box:
![screen shot 2018-09-10 at 3 45 58 pm](https://user-images.githubusercontent.com/8875863/45320477-c0969b80-b510-11e8-8a90-2433ce18bf69.png)
![screen shot 2018-09-10 at 3 46 21 pm](https://user-images.githubusercontent.com/8875863/45320479-c1c7c880-b510-11e8-8375-b74f3f6f900f.png)
![screen shot 2018-09-10 at 3 46 28 pm](https://user-images.githubusercontent.com/8875863/45320481-c3918c00-b510-11e8-9004-cf919aaf005d.png)
